---
- name: Verification where is running - InfraRed or Standalone
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  vars:
      hypervisor_name: 127.0.0.1
  
  tasks:

  - name: Add Hypervisor hosts to host list when run standalone
    add_host:
        name: "{{ hypervisor_name }}"
        groups: hypervisor
    when:  "'hypervisor' not in groups"
    
- name: Compare REST API Performance Sanity Tests
  hosts: hypervisor
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/restapi-perf.yml
  vars:
   test_run_name: compare-restapi # test run name
   baseline_run_name: baseline-test
   current_run_name: current-test
   build_num: osp-13
   perf_monitor: false 

  environment:
   JMETER_HOME: /opt/apache-jmeter-5.2.1

  tasks: 

  - name: Undercloud IP
    shell: "sudo virsh domifaddr undercloud-0 |grep ipv4 | awk 'FNR == 2 {print $4}' | awk -F '/' '{print $1}'"
    register: uc_node_ip
  
  - name: System-OS
    shell: "sudo cat /etc/system-release"
    register: system_os
  
  - name: Creation directory for test result
    include_tasks: tasks/mkdir-compare-results.yml

  - name: Merge test results
    include_tasks: tasks/merge-results.yml
    
  - name: Generate API Trx charts
    include_tasks: tasks/api-trx-compare-charts.yml

  - name: Generate PerfMon charts
    include_tasks: tasks/perfmon-compare-charts.yml
    when: perf_monitor
    
  - name: Copy tests results
    include_tasks: tasks/copy-compare-results.yml

  - name: Generate test report
    include_tasks: tasks/report-restapi-compare.yml

# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

