---
- name: Verification where is running - InfraRed or Standalone
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  vars:
      hypervisor_name: 127.0.0.1
  
  tasks:

  - name: Add Hypervisor hosts to host list when run standalone
    add_host:
        name: "{{ hypervisor_name }}"
        groups: hypervisor
    when:  "'hypervisor' not in groups"
    
- name: Delete WAN emulation
  hosts: hypervisor
  remote_user: root
  gather_facts: no
  vars:
   tc_device: br-ctlplane
   tc_delay: 50
   tc_limit: 15000000

  tasks: 

  - name: Undercloud IP
    shell: "sudo virsh domifaddr undercloud-0 |grep ipv4 | awk 'FNR == 2 {print $4}' | awk -F '/' '{print $1}'"
    register: uc_node_ip

  - name: Start tc qdisc del for for incoming traffic
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo tc qdisc del dev ifb0 root netem delay {{ tc_delay }}ms limit {{ tc_limit }}\""

  - name: Remove device to be ingress
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo tc qdisc del dev {{ tc_device }} ingress\""

  - name: Stop interface ifb
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo ip link set dev ifb0 down\""

  - name: Remove interface ifb for incoming traffic 
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo modprobe -r ifb\""

  - name: Start tc qdisc del for outgoing traffic
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo tc qdisc del dev {{ tc_device }} root netem delay {{ tc_delay }}ms limit {{ tc_limit }}\""

# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

