---
- name: Verification where is running - InfraRed or Standalone
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  vars:
      hypervisor_name: 127.0.0.1
  
  tasks:

  - name: Add Hypervisor hosts to host list when run standalone
    add_host:
        name: "{{ hypervisor_name }}"
        groups: hypervisor
    when:  "'hypervisor' not in groups"
    
- name: Run Data Plane Load Test
  hosts: hypervisor
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/load.yml
  vars:
   test_run_name: load-test
   build_num: osp-13
   thread_count: 1 
   thread_rampup: 100 
   image_name: rhel
   flavor_ref: 2 
   vm_amount: 1 
   cpu_workers: 2 
   cpu_percent: 50 
   vm_workers: 2 
   vm_mbytes: 512 
   hdd_workers: 2 
   hdd_gbytes: 2 
   stress_time_sec: 600 
   perf_monitor: false 
   ssl_mode: false 
   iperf_host: 10.35.64.12 #127.0.0.1
   iperf_user: root
   iperf_pass: qum5net

  environment:
   JMETER_HOME: /opt/apache-jmeter-4.0

  tasks: 

  - name: Undercloud IP
    shell: "sudo virsh domifaddr undercloud-0 |grep ipv4 | awk 'FNR == 2 {print $4}' | awk -F '/' '{print $1}'"
    register: uc_node_ip

  - set_fact:
      iperf_host: "{{ uc_node_ip.stdout }}"
    when: iperf_host == "127.0.0.1"
  
  - name: System-OS
    shell: "sudo cat /etc/system-release"
    register: system_os

  - name: Gathering Stack env information
    include_tasks: tasks/get-stack-info.yml

  - name: Creation directory for test result
    include_tasks: tasks/mkdir-results.yml
   
  - name: Gathering Stack status
    include_tasks: tasks/get-stack-status.yml
    vars: 
      status_file_name: stack-start-test.txt
    
  - name: Run async JMeter test script
    include_tasks: tasks/run-jmeter-ping.yml
    when:  stress_time_sec == "0" or not stress_time_sec
    
  - block:

    - name: Run JMeter test script
      include_tasks: tasks/run-jmeter-load.yml

    - name: Generate API Trx charts
      include_tasks: tasks/api-trx-charts.yml

    - name: Generate PerfMon charts
      include_tasks: tasks/perfmon-charts.yml
      when: perf_monitor

    - name: Generate test report
      include_tasks: tasks/report-load.yml

    when: stress_time_sec
    
# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

