---
- name: Verification where is running - InfraRed or Standalone
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  vars:
      hypervisor_name: 127.0.0.1
  
  tasks:

  - name: Add Hypervisor hosts to host list when run standalone
    add_host:
        name: "{{ hypervisor_name }}"
        groups: hypervisor
    when:  "'hypervisor' not in groups"
    
- name: Upload test results to remote server
  hosts: hypervisor
  remote_user: root
  gather_facts: no
  vars:
   test_run_name: upload-patch
   patch_location: /opt/patches/
   patch_file: shoot.sh

  tasks: 

  - name: Indetify UC IP on virt
    shell: "sudo virsh domifaddr undercloud-0 |grep ipv4 | awk 'FNR == 2 {print $4}' | awk -F '/' '{print $1}'"
    register: uc_node_ip

  - name: Upload patch to undercloud /home/stack/ directory
    shell: "scp {{ patch_location }}{{ patch_file }} root@{{ uc_node_ip.stdout }}:/home/stack/"

# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

