  - name: Date and Time
    shell: "date +'%Y-%m-%d-%I-%M-%S'"
    register: datestr
    
  - name: Controller nodes count
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list | grep controller | wc -l\""
    register: contr_count

  - name: Compute nodes count
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list | grep compute | wc -l\""
    register: comp_count

  - name: Ceph nodes count
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list | grep ceph | wc -l\""
    register: ceph_count

  - name: Get Contr-0 Node 
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name controller-0 -f value -c Networks|awk -F = '{print \\$2}'\""
    register: contr_0_node

  - name: Get Contr-1 Node 
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name controller-1 -f value -c Networks|awk -F = '{print \\$2}'\""
    register: contr_1_node
    
  - name: Get Comp-0 Node 
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name compute-0 -f value -c Networks|awk -F = '{print \\$2}'\""
    register: comp_0_node

  - name: Get Ceph-0 Node 
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name ceph-0 -f value -c Networks|awk -F = '{print \\$2}'\""
    register: ceph_0_node
#    when: ceph_count.stdout != "0"
    
  - name: Get Contr Node list
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name controller -f value -c Networks|awk -F = '{print \\$2}'\""
    register: contr_nodes

  - name: Get Compute Node list
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name compute -f value -c Networks|awk -F = '{print \\$2}'\""
    register: comp_nodes

  - name: Get Ceph Node list
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/stackrc && openstack server list --name ceph -f value -c Networks|awk -F = '{print \\$2}'\""
    register: ceph_nodes
    when: ceph_count.stdout != "0"

# --------------------------------------------------------------------------------------------------------------------------------------
# Undercloud node
# --------------------------------------------------------------------------------------------------------------------------------------

  - name: Vendor name UC
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"cat /sys/devices/virtual/dmi/id/sys_vendor\""
    register: uc_vendor

  - name: Product name UC
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"cat /sys/devices/virtual/dmi/id/product_name\""
    register: uc_product

  - name: OS name UC 
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"cat /etc/redhat-release\""
    register: uc_os

  - name: CPU count UC
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"cat /proc/cpuinfo |  grep processor | wc -l\""
    register: uc_cpu_count

  - name: CPU model UC
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"grep -m 1 'model name' /proc/cpuinfo |awk '{print \\$4,\\$5,\\$6,\\$7,\\$8,\\$9,\\$10}'\""
    register: uc_cpu_model

  - name: Memory amount UC
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"cat /proc/meminfo |grep MemTotal: | awk '{print \\$2,\\$3}'\""
    register: uc_mem

# --------------------------------------------------------------------------------------------------------------------------------------
# Controller node
# --------------------------------------------------------------------------------------------------------------------------------------
    
  - name: Vendor name Controller
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ contr_0_node.stdout }} \"cat /sys/devices/virtual/dmi/id/sys_vendor\""
    register: contr_vendor

  - name: Product name Controller
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ contr_0_node.stdout }} \"cat /sys/devices/virtual/dmi/id/product_name\""
    register: contr_product

  - name: OS name Controller
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ contr_0_node.stdout }} \"cat /etc/redhat-release\""
    register: contr_os

  - name: CPU Count Controller
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ contr_0_node.stdout }} \"cat /proc/cpuinfo |  grep processor | wc -l\""
    register: contr_cpu_count

  - name: CPU Model Controller
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ contr_0_node.stdout }} \"grep -m 1 'model name' /proc/cpuinfo |awk '{print \\$4,\\$5,\\$6,\\$7,\\$8,\\$9,\\$10}'\""
    register: contr_cpu_model
    
  - name: Memory Controller
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ contr_0_node.stdout }} \"cat /proc/meminfo |grep MemTotal: | awk '{print \\$2,\\$3}'\""
    register: contr_mem

# --------------------------------------------------------------------------------------------------------------------------------------
# Compute node
# --------------------------------------------------------------------------------------------------------------------------------------
    
  - name: Vendor name Compute
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ comp_0_node.stdout }} \"cat /sys/devices/virtual/dmi/id/sys_vendor\""
    register: comp_vendor

  - name: Product name Compute
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ comp_0_node.stdout }} \"cat /sys/devices/virtual/dmi/id/product_name\""
    register: comp_product

  - name: OS name Compute
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ comp_0_node.stdout }} \"cat /etc/redhat-release\""
    register: comp_os

  - name: CPU Count Compute
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ comp_0_node.stdout }} \"cat /proc/cpuinfo |  grep processor | wc -l\""
    register: comp_cpu_count

  - name: CPU Model Compute
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ comp_0_node.stdout }} \"grep -m 1 'model name' /proc/cpuinfo |awk '{print \\$4,\\$5,\\$6,\\$7,\\$8,\\$9,\\$10}'\""
    register: comp_cpu_model
    
  - name: Memory Compute
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ comp_0_node.stdout }} \"cat /proc/meminfo |grep MemTotal: | awk '{print \\$2,\\$3}'\""
    register: comp_mem

# --------------------------------------------------------------------------------------------------------------------------------------
# Ceph node
# --------------------------------------------------------------------------------------------------------------------------------------
    
  - name: Vendor name Ceph
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ ceph_0_node.stdout }} \"cat /sys/devices/virtual/dmi/id/sys_vendor\""
    register: ceph_vendor
    when: ceph_count.stdout != "0"

  - name: Product name Ceph
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ ceph_0_node.stdout }} \"cat /sys/devices/virtual/dmi/id/product_name\""
    register: ceph_product
    when: ceph_count.stdout != "0"

  - name: OS name Ceph
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ ceph_0_node.stdout }} \"cat /etc/redhat-release\""
    register: ceph_os
    when: ceph_count.stdout != "0"

  - name: CPU Count Ceph
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ ceph_0_node.stdout }} \"cat /proc/cpuinfo |  grep processor | wc -l\""
    register: ceph_cpu_count
    when: ceph_count.stdout != "0"

  - name: CPU Model Ceph
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ ceph_0_node.stdout }} \"grep -m 1 'model name' /proc/cpuinfo |awk '{print \\$4,\\$5,\\$6,\\$7,\\$8,\\$9,\\$10}'\""
    register: ceph_cpu_model
    when: ceph_count.stdout != "0"
    
  - name: Memory Ceph
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ ceph_0_node.stdout }} \"cat /proc/meminfo |grep MemTotal: | awk '{print \\$2,\\$3}'\""
    register: ceph_mem
    when: ceph_count.stdout != "0"
    
# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

