
# --------------------------------------------------------------------------------------------------------------------------------------
# Collect Stack configuration
# --------------------------------------------------------------------------------------------------------------------------------------

  - name: Create puddle_version file
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"touch /tmp/puddle-version.txt\""

  - name: Get puddle_version
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo cat /etc/yum.repos.d/latest-installed | tr -d \" \"\""
    register: cur_puddle_version

  - name: Store puddle_version
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"echo '{{ cur_puddle_version.stdout }}'  > /tmp/puddle-version.txt\""

  - name:  Copy custer status file 
    shell: "scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }}:/tmp/puddle-version.txt /tmp/puddle-version.txt"
    
# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

