# ------------------------------------------------------------------------------
# Openstack Overcloud Flavors creation flow
# ------------------------------------------------------------------------------
    
  - name: Create m1.tiny flavor in Openstack Overcloud
    shell: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/overcloudrc && openstack flavor create --public m1.tiny --id 1 --ram 512 --disk 1 --vcpus 1\""
    ignore_errors: yes

  - name: Create m1.small flavor in Openstack Overcloud
    shell: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/overcloudrc && openstack flavor create --public m1.small --id 2 --ram 2048 --disk 20 --vcpus 1\""
    ignore_errors: yes

  - name: Create m1.medium flavor in Openstack Overcloud
    shell: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/overcloudrc && openstack flavor create --public m1.medium --id 3 --ram 4096 --disk 40 --vcpus 2\""
    ignore_errors: yes

  - name: Create m1.large flavor in Openstack Overcloud
    shell: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/overcloudrc && openstack flavor create --public m1.large --id 4 --ram 8192 --disk 80 --vcpus 4\""
    ignore_errors: yes

  - name: Create m1.xlarge flavor in Openstack Overcloud
    shell: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/overcloudrc && openstack flavor create --public m1.xlarge --id 5 --ram 16384 --disk 160 --vcpus 8\""
    ignore_errors: yes

  - name: Create m1.nano flavor in Openstack Overcloud
    shell: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo -u stack cd /home/stack/ && source /home/stack/overcloudrc && openstack flavor create --public m1.nano --id 6 --ram 64 --disk 1 --vcpus 1\""
    ignore_errors: yes

# ------------------------------------------------------------------------------