# --------------------------------------------------------------------------------------------------------------------------------------

  - name: Date and Time
    shell: "date +'%Y-%m-%d-%I-%M-%S'"
    register: datestr
      
  - name: Container status
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ uc_node_ip.stdout }} \"sudo echo '{{ datestr.stdout }}' - Container restarted is  - '{{ container_name }}' >> /tmp/disruptive-test-result.txt\""
      
  - name: Docker reboot container
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ node_name }} \"sudo docker restart '{{ container_name }}'\""
    become: true
    become_user: stack
    delegate_to: '{{ uc_node_ip.stdout }}'
      
  - name: Waiting for Docker container is Up
    shell: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heat-admin@{{ node_name }} \"sudo docker ps -f name='{{ container_name }}'\""
    become: true
    become_user: stack
    delegate_to: '{{ uc_node_ip.stdout }}'
    register: container_status
    until: ("Up" in container_status.stdout) or ("Restarting" in  container_status.stdout)
    retries: 10
    delay: 3
#  - debug: var=container_status.stdout_lines

  - pause:
      minutes: 1

# --------------------------------------------------------------------------------------------------------------------------------------
# END
# --------------------------------------------------------------------------------------------------------------------------------------

